services:
  postgres:
    image: postgres:15-alpine
    container_name: ${DB_CONTAINER}
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 5s
      retries: 5

  usertask:
    build: .
    image: usertask
    container_name: usertask_service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./docs:/usr/share/nginx/html/docs
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/docs/swagger.json

volumes:
  postgres_data: