version: '3.9'

services:
  usertask:
    build: .
    image: usertask
    container_name: usertask_service
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

  postgres:
    image: postgres:15-alpine
    container_name: ${DB_CONTAINER}
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
